---
- name: EOS common files
  ansible.builtin.copy:
    dest: /etc/
    src: "{{ playbook_dir }}/../additions/eos_setup/{{ eos_common_files }}"
    owner: daemon
    group: daemon
    mode: '0400'
    force: true
  loop_control:
    loop_var: eos_common_files
  with_items:
    - quarkdb.pass
    - eos.keytab

- name: EOS eos_env configuration
  ansible.builtin.template:
    src: "{{ playbook_dir }}/../additions/eos_setup/eos_env.j2"
    dest: /etc/sysconfig/eos_env
    owner: root
    group: root
    mode: '0644'
    force: true
  ignore_errors: true

- name: mkdir EOS directories
  ansible.builtin.file:
    owner: daemon
    group: daemon
    mode: 'u=rwX,g=rX,o=rX'
    recurse: false
    state: directory
    path : "{{ eos_common_dirs }}"
  loop_control:
    loop_var: eos_common_dirs
  with_items:
    - /var/eos
    - /var/eos/auth
    - /var/eos/html
    - /var/eos/fst
    - /var/eos/md
    - /var/eos/mgm
    - /var/eos/mq
    - /var/eos/ns-queue
    - /var/eos/qos
    - /var/eos/report
    - /var/eos/stage
    - /var/eos/wfe
    - /var/spool/eos
    - /var/spool/eos/admin
    - /var/spool/eos/core/mgm
    - /var/spool/eos/core/mq
    - /var/spool/eos/core/fst
    - /var/log/eos

- name: EOS default acl permissions
  ansible.posix.acl:
    entity: daemon
    etype: user
    permissions: rw
    state: present
    default: true
    path: "{{ eos_common_dirs_def_acl }}"
  loop_control:
    loop_var: eos_common_dirs_def_acl
  with_items:
    - /var/eos
    - /var/eos/auth
    - /var/eos/html
    - /var/eos/fst
    - /var/eos/md
    - /var/eos/mgm
    - /var/eos/mq
    - /var/eos/ns-queue
    - /var/eos/qos
    - /var/eos/report
    - /var/eos/stage
    - /var/eos/wfe
    - /var/spool/eos
    - /var/log/eos

#- name: "Dump ansible_facts"
#  debug:
#    msg: "{{ ansible_facts | to_nice_json }}"

