---
- include_tasks: pkg_tuned_task.yml

- name: add Hiroshima tuning profile
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/tuned/hiroshima"
    dest: /etc/tuned/
    owner: root
    group: root
    mode: '0644'
    force: true

- name: tuned role
  vars:
    daemon: "{{ tuned_daemon_mode | default('true') }}"
    reapply_sysctl: true
    use_recommended_profile: false
    enable_recommend: false
    dynamic_tuning: false

  include_role:
    name: linux-system-roles.tuned
