---
- name: Include pkg_chrony_task.yml
  ansible.builtin.include_tasks: pkg_chrony_task.yml

- name: Chrony configuration
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/chrony/chrony.conf.client_{{ chrony_base_ip }}"
    dest: /etc/chrony.conf
    mode: "0644"
    owner: root
    group: root
    backup: true
    force: true
  register: chrony_is_configured

- name: Enable and start chronyd
  ansible.builtin.systemd:
    name: chronyd
    state: restarted
    enabled: true
  register: chrony_restarted

- name: Configure time system
  ansible.builtin.command: "{{ item }}"
  with_items:
    - /usr/bin/timedatectl set-local-rtc 0
    - /usr/bin/timedatectl set-timezone Asia/Tokyo #Europe/Bucharest #Tokyoかな？
    - /usr/bin/timedatectl set-ntp 1
  when: chrony_restarted is succeeded
  changed_when: true