---
- name: include repo_cernvm_task.yml
  ansible.builtin.include_tasks: repo_cernvm_task.yml

- name: Install CVMFS packages and dependencies
  ansible.builtin.dnf:
    name: [ 'autofs', 'cvmfs', 'cvmfs-config-default' ]
    state: present
    enablerepo: "cernvm,cernvm-config"
    disablerepo: "UMD*"
  tags: packages

