---
- name: Install misc tools for server admin - EL9
  ansible.builtin.dnf:
    name:
      - mc
      - htop
      - iotop-c
      - jq
      - jc
      - ps_mem
      - the_silver_searcher
      - freeipmi
      - freeipmi-bmc-watchdog
      - freeipmi-ipmidetectd
      - freeipmi-ipmiseld
      - ipmievd
      - ipmitool
    state: present
    update_cache: false
    enablerepo: "epel"
  when: ansible_facts[ 'distribution' ] == 'AlmaLinux'

#- name: Create htop conf dir
#  ansible.builtin.file:
#    path: /root/.config/htop
#    state: directory

#- name: Configure htop EL9
#  ansible.builtin.copy:
#    src: "{{ playbook_dir }}/../additions/htop/htoprc_el9"
#    dest: /root/.config/htop/htoprc
#    owner: root
#    group: root
#    mode: '0644'
#    force: true
#  when: ansible_facts[ 'distribution' ] == 'AlmaLinux' or ansible_facts[ 'distribution' ] == 'Fedora'
