---
- name: Install chrony EL9
  ansible.builtin.yum:
    name: chrony
    state: present
  when: ( ansible_facts['distribution'] == 'AlmaLinux' and ansible_facts['distribution_major_version'] == '9' ) or ansible_facts['distribution'] == 'Fedora'
  tags: packages