---
- name: Include pkg_yum-utils_task.yml
  include_tasks: pkg_yum-utils_task.yml

- name: Import WLCG key
  ansible.builtin.rpm_key:
    state: present
    key: http://linuxsoft.cern.ch/wlcg/RPM-GPG-KEY-wlcg


- name: Install WLCG repository EL9
  ansible.builtin.dnf:
    name: http://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-repo-1.0.0-1.el9.noarch.rpm
    state: present
  when: ansible_facts[ 'distribution' ] == 'AlmaLinux'
  tags: repo
