---
- name: Configure lm_sensors
  ansible.builtin.command: /usr/sbin/sensors-detect --auto
  register: lmsensors_config

- name: Enable and start
  ansible.builtin.systemd:
    name: lm_sensors
    state: restarted
    enabled: true
  when: lmsensors_config is succeeded