---
- name: Raid-check configuration
  ansible.builtin.template:
    src: "{{ playbook_dir }}/../additions/storage_cmds/sysconfig_raid-check.j2"
    dest: /etc/sysconfig/raid-check
    owner: root
    group: root
    mode: '0644'
    force: true

- name: Smartd loggind directory
  ansible.builtin.file:
    path: /etc/systemd/system/raid-check.timer.d/
    state: directory
  when: ( ansible_facts['distribution'] == 'AlmaLinux' and ( ansible_facts['distribution_major_version'] | int  > 7 ) ) or ansible_facts['distribution'] == 'Fedora'

- name: Raid-check timing (systemd) - EL9
  ansible.builtin.template:
    src: "{{ playbook_dir }}/../additions/storage_cmds/systemd_raid-check.j2"
    dest: /etc/systemd/system/raid-check.timer.d/override.conf
    owner: root
    group: root
    mode: '0644'
    force: true
  when: ( ansible_facts['distribution'] == 'AlmaLinux' and ( ansible_facts['distribution_major_version'] | int  > 7 ) ) or ansible_facts['distribution'] == 'Fedora'

- name: Raid-check timing (systemd) - start timer
  ansible.builtin.systemd:
    name: raid-check.timer
    state: started
    daemon_reload: true
    enabled: true
  when: ( ansible_facts['distribution'] == 'AlmaLinux' and ( ansible_facts['distribution_major_version'] | int  > 7 ) ) or ansible_facts['distribution'] == 'Fedora'