---
- include_tasks: repo_wlcg_task.yml
###    name: [ 'http://linuxsoft.cern.ch/wlcg/centos7/x86_64/mlsensor-1.2.6-1.el7.noarch.rpm' ]

- name: Install mlsensor EL9
  ansible.builtin.dnf:
    name: [ 'mlsensor' ]
    state: present
    enablerepo: "epel,wlcg"
    disablerepo: "UMD*"
  when: ( ansible_facts[ 'distribution' ] == 'AlmaLinux' and ansible_facts[ 'distribution_major_version' ] == '9' ) or ansible_facts[ 'distribution' ] == 'Fedora'
  tags: packages