---
- name: Enable EPEL Repository on EL9
  ansible.builtin.dnf:
    name: epel-release
    state: present
    update_cache: false
  when: ansible_facts['distribution'] == 'AlmaLinux' and ansible_facts['distribution_major_version'] == '9'