---
- name: Sync storage tools
  ansible.builtin.copy:
    dest: /root/bin/
    src: "{{ playbook_dir }}/../additions/storage_cmds/{{ mdadm_scripts }}"
    owner: root
    group: root
    mode: '0700'
    force: true
  loop_control:
    loop_var: mdadm_scripts
  with_items:
    - md_readd_dev
    - md_rm_dev
    - md_check
    - md_check_stop
    - md_health
    - iostat_md
    - list_storage
    - smartctl_dump
    - smart_temp_report

- name: Sync md format tools
  ansible.builtin.copy:
    dest: /root/bin/md_mkformat/
    src: "{{ playbook_dir }}/../additions/storage_cmds/md_mkformat/{{ md_format_scripts }}"
    owner: root
    group: root
    mode: '0600'
    force: true
  loop_control:
    loop_var: md_format_scripts
  with_items:
    - create_md_array
    - format_md_component
    - format_mdraid
    - select_disk_range

- name: Add cron job for smart_temp_report
  ansible.builtin.copy:
    dest: "/etc/cron.d/smart_temp_report"
    force: true
    group: root
    owner: root
    mode: 0644
    content: |
        SHELL=/usr/bin/bash
        PATH=/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
        MAILTO=root
        */2 * * * * root /root/bin/smart_temp_report &> /tmp/smart_temp_report.log