---
- name: Create location for individual tuning scripts
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
  loop:
    - /root/tuning.d
    - /root/bin

- name: Copy tuning appling script
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/root_bin/apply_tuning"
    dest: /root/bin/
    owner: root
    group: root
    mode: '0700'
    force: true

- name: Install cron for tuning script
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/cron.d/tuning.cron"
    dest: /etc/cron.d/tuning
    owner: root
    group: root
    mode: '0644'
    force: true

- name: Clean up current tunes
  ansible.builtin.command:
    cmd: find /root/tuning.d -type f -delete
  args:
    chdir: /root/tuning.d

- name: Copy tuning scripts
  ansible.builtin.copy:
    owner: root
    group: root
    mode: '700'
    force: true
    dest: /root/tuning.d/
    src: "{{ tuning_item }}"
  loop_control:
    loop_var: tuning_item
  loop: "{{ tuning_list }}"

- name: Apply tuning scripts
  ansible.builtin.command: /root/bin/apply_tuning