---
- include_tasks: repo_eos_task.yml

- name: Install EOS packages EL9
  ansible.builtin.dnf:
    name: [ 'eos-server', 'eos-client', 'jemalloc', 'jemalloc-devel' ]
    state: present
    enablerepo: "eos-diopside, eos-diopside-dep"
  tags: packages
  when: ansible_facts['distribution'] == 'AlmaLinux'