---
- name: Restart EOS MGM services
  hosts: eos_mgm
  become: yes

  tasks:
    - name: Stop eos5-mgm@mgm-service
      ansible.builtin.systemd:
        name: eos5-mgm@mgm
        state: stopped

    - name: Start eos5-mgm@mgm-service
      ansible.builtin.systemd:
        name: eos5-mgm@mgm
        state: started
